<?php

/**
 * @file
 * Module definition.
 */

const AUTH0_DEFAULT_SCOPES = 'openid email profile';
const AUTH0_DEFAULT_SIGNING_ALGORITHM = 'RS256';
const AUTH0_DEFAULT_USERNAME_CLAIM = 'nickname';
const AUTH0_MODULE_VERSION = '8.x-2.4';

use Drupal\Core\Render\Element;
use Drupal\Core\Block\BlockPluginInterface;
use Symfony\Component\HttpFoundation\RedirectResponse;
use Drupal\Core\Url;
use Drupal\auth0\Auth0BlockUserLoginViewBuilder;

/**
 * Implements hook_theme().
 */
function auth0_theme() {
  // Replaces a form with the lock widget.
  return [
    'auth0_login' => [
      'template' => 'auth0-login',
      'variables' => [
        'loginCSS' => \Drupal::config('auth0.settings')->get('auth0_login_css'),
        'sso' => \Drupal::config('auth0.settings')->get('auth0_redirect_for_sso'),
        'loginLink' => '',
      ],
    ],
  ];
}

/**
 * Implements hook_ENTITY_TYPE_delete().
 */
function auth0_user_delete($account) {
  // Handle users deletion, it should delete the Auth0 profile.
  \Drupal::database()->delete('auth0_user')
    ->condition('drupal_id', $account->uid->value)
    ->execute();
}

/**
 * Implements hook_form_alter().
 *
 * Replace the user login forms with the Auth0 login widget.
 */
function auth0_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) {
  $config = \Drupal::config('auth0.settings');
  // If replacing the forms is disabled, then skip making alterations.
  if (!$config->get('auth0_replace_forms')) {
    return;
  }

  if (($form_id == 'user_login_form' || $form_id == 'user_login') && auth0_enabled('login')) {
    _auth0_form_replace_with_lock($form, 'signin');
  }

  // If Auth0 controls the user database.
  if ($form_id == 'user_register_form' && auth0_enabled('signup')) {
    _auth0_form_replace_with_lock($form, 'signup');
  }
  if ($form_id == 'user_pass' && auth0_enabled('reset')) {
    _auth0_form_replace_with_lock($form, 'reset');
  }
  // If the settings say to remove the signup altogether.
  if (!$config->get('auth0_allow_signup')) {
    if ($form_id == 'user_register_form' || $form_id == 'user_pass') {
      \var_dump($config->get('auth0_allow_signup'));
      // @TODO: Remove the user signup option.
      $url = Url::fromRoute('auth0.login');
      $response = new RedirectResponse($url->toString());
      $request = \Drupal::request();
      // Save the session so things like messages get saved.
      $request->getSession()->save();
      $response->prepare($request);
      // Make sure to trigger kernel events.
      \Drupal::service('kernel')->terminate($request, $response);
      $response->send();
    }
  }
}

/**
 * Determine if Auth0 is enabled and can be used.
 */
function auth0_enabled($operation = '') {
  $config = \Drupal::config('auth0.settings');
  $out = FALSE;

  // Check that the module has been configured.
  if (
    $config->get('auth0_domain') &&
    $config->get('auth0_client_id') &&
    $config->get('auth0_client_secret')
    ) {

    // Default to on if the module is configured.
    $out = TRUE;

    // See if our settings allow us to override the registration form.
    if ($operation == 'signup' || $operation == 'reset') {
      $out = (bool) $config->get('auth0_allow_signup');
    }
  }

  // Allow other modules to override the status.
  \Drupal::moduleHandler()->alter('auth0_enabled', $out, $operation);

  return $out;
}

/**
 * Replace a form with the lock widget.
 */
function _auth0_form_replace_with_lock(&$form, $mode = 'signin') {
  // Remove the old form elements.
  foreach (Element::children($form) as $child) {
    unset($form[$child]);
  }
  $config = \Drupal::config('auth0.settings');
  $twigFilePath = \Drupal::service('extension.list.module')->getPath('auth0') . '/templates/auth0-login.html.twig';
  $twigService = \Drupal::service('twig');
  $authController = Drupal\auth0\Controller\AuthController::create(\Drupal::getContainer());
  $template = $twigService->loadTemplate($twigFilePath);
  $request = \Drupal::request();
  $lockExtraSettings = $config->get('auth0_lock_extra_settings');
  if (trim($lockExtraSettings) == "") {
    $lockExtraSettings = "{}";
  }
  $sso = $config->get('auth0_redirect_for_sso');
  $returnTo = $request->request->get('returnTo', $request->query->get('returnTo', NULL));
  $loginLink = $authController->loginLink($returnTo);
  $markup = $template->render(['sso' => $sso, 'loginLink' => $loginLink, 'loginCSS' => \Drupal::config('auth0.settings')->get('auth0_login_css')]);
  $settings = $authController->lockSettings($lockExtraSettings, $returnTo);
  // Add an Auth0 Lock widget.
  $form['auth0'] = [
    '#type' => 'markup',
    '#markup' => $markup,
  ];
  if (!$sso) {
    $form['#attached']['drupalSettings']['auth0'] = $settings;
    $form['#attached']['library'][] = 'auth0/auth0.lock';
  }
}

/**
 * Implements hook_library_info_build().
 */
function auth0_library_info_build() {
  $config = \Drupal::config('auth0.settings');
  return [
    'auth0.widget' => [
      'js' => [
        $config->get('auth0_widget_cdn') => [
          'type' => 'external',
        ],
      ],
    ],
  ];
}

/**
 * Implements hook_block_view_BASE_BLOCK_ID_alter().
 *
 * Adds a pre-render callback which allows changing the block content before
 * rendering.
 */
function auth0_block_view_user_login_block_alter(array &$build, BlockPluginInterface $block) {
  if (!\Drupal::config('auth0.settings')->get('auth0_allow_signup')) {
    $build['#pre_render'][] = [Auth0BlockUserLoginViewBuilder::class, 'preRender'];
  }
}
